"""
Explainable AI Page — Professional redesign
Tabs: Classification XAI | Part 4.5 - 3D XAI | Part 4.6 - Point-Targeted |
      Part 4.6B - Multi-Point | Part 4.6C - Quantitative | Part 4.6D - Visual Inspection
"""

from pathlib import Path
import json
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use("Agg")

from ui.common import navigate, safe, pct

# ── Paths ───────────────────────────────────────────────────────────────────
_APP_DIR   = Path(__file__).resolve().parents[1]
_PROJ_ROOT = _APP_DIR.parent
_SEG       = _PROJ_ROOT / "outputs" / "segmentation"

_PART45    = _SEG / "rsna_part45_3d_xai"
_PART46    = _SEG / "rsna_part46_point_targeted_3d_xai"
_PART46B   = _SEG / "rsna_part46b_multi_point_3d_xai"
_PART46C   = _SEG / "rsna_part46c_xai_summary"
_PART46D   = _SEG / "rsna_part46d_xai_visual_inspection"

_DISEASE_OPTIONS = [
    "Spinal Canal Stenosis",
    "Left Neural Foraminal Narrowing",
    "Right Neural Foraminal Narrowing",
    "Left Subarticular Stenosis",
    "Right Subarticular Stenosis",
]

_DISEASE_FILE = {
    "Spinal Canal Stenosis":            "spinal_canal_stenosis",
    "Left Neural Foraminal Narrowing":  "left_neural_foraminal_narrowing",
    "Right Neural Foraminal Narrowing": "right_neural_foraminal_narrowing",
    "Left Subarticular Stenosis":       "left_subarticular_stenosis",
    "Right Subarticular Stenosis":      "right_subarticular_stenosis",
}


def _session():
    s = st.session_state.get("analysis_session")
    return s if s and s.has_prediction else None


def _page_header():
    st.markdown("""
    <div class="page-title-row">
        <h2>🔬 Explainable AI</h2>
        <p>Classification and 3D Swin-UNETR explainability analysis — Grad-CAM · 3D Attribution · Quantitative XAI</p>
    </div>
    """, unsafe_allow_html=True)


def _research_disclaimer():
    st.markdown("""
    <div class="research-disclaimer">
        <strong>⚠️ Research Interpretation Only</strong>
        XAI outputs represent model-attribution/evidence patterns generated by completed experiments.
        They should not be interpreted as clinically validated lesion boundaries or diagnostic evidence.
        The 3D Swin-UNETR localization outputs are derived from point/localization annotations and
        should not be presented as manually validated voxel-level segmentation masks.
    </div>
    """, unsafe_allow_html=True)


# ── Tab 1: Classification XAI ────────────────────────────────────────────────

def _tab_classification_xai():
    s = _session()

    if s is None:
        st.info("Run an MRI analysis first. Classification XAI (Grad-CAM) requires an active inference session.")
        if st.button("🩻 Go to MRI Analysis", type="primary", key="xai_cls_goto"):
            navigate("🩻 MRI Analysis")
        return

    c1, c2, c3 = st.columns(3)
    with c1:
        st.metric("Prediction",   safe(s.predicted_class))
    with c2:
        st.metric("Confidence",   f"{pct(s.confidence):.2f}%")
    with c3:
        st.metric("Target Class", safe(s.predicted_class))

    st.markdown("---")

    if s.has_xai:
        st.success("✅ Grad-CAM explanation is available for this analysis.")
    else:
        st.info("Generate Grad-CAM. This uses the existing checkpoint — no retraining.")

    if st.button("🔬 Generate XAI Explanation", type="primary", use_container_width=False, key="generate_xai_cls"):
        with st.spinner("Generating Grad-CAM from the existing trained model..."):
            try:
                if len(s.selected_files) != 3:
                    raise RuntimeError("XAI requires exactly 3 adjacent DICOM slices from the current analysis.")
                from xai_dashboard import explain_dicom_series
                result = explain_dicom_series(
                    [str(p) for p in s.selected_files],
                    target_class=s.predicted_class_id,
                    output_name="dashboard_current_analysis",
                )
                outputs = result.get("outputs", {}) if isinstance(result, dict) else {}
                s.xai_result  = result
                s.xai_paths   = {k: str(v) for k, v in outputs.items() if v}
                s.gradcam_generated = bool(s.xai_paths)
                st.success("Grad-CAM generated successfully.")
                st.rerun()
            except Exception as exc:
                st.error("XAI generation failed. The model checkpoint was not modified.")
                with st.expander("Technical details"):
                    st.exception(exc)

    if not s.has_xai or not s.xai_paths:
        return

    st.markdown("---")
    st.markdown('<div class="section-title" style="margin-bottom:0.8rem;">🖼️ Grad-CAM Visualization</div>', unsafe_allow_html=True)

    paths = s.xai_paths
    images = [
        (paths.get("middle_slice"), "MRI Middle Slice"),
        (paths.get("heatmap"),      "Grad-CAM Heatmap"),
        (paths.get("overlay"),      "Model Attention Overlay"),
    ]
    cols = st.columns(3)
    for col, (path, title) in zip(cols, images):
        with col:
            st.markdown(f"**{title}**")
            if path and Path(path).exists():
                st.image(path, use_container_width=True)
            else:
                st.warning("Image not found.")

    panel = paths.get("panel")
    if panel and Path(panel).exists():
        st.markdown("**XAI Summary Panel**")
        st.image(panel, use_container_width=True)

    xai = s.xai_result.get("xai", {}) if isinstance(s.xai_result, dict) else {}
    if xai:
        c1, c2, c3 = st.columns(3)
        with c1: st.metric("Feature Shape", str(xai.get("feature_shape", "N/A")))
        with c2: st.metric("CAM Mean",       f"{float(xai.get('cam_mean', 0)):.4f}")
        with c3: st.metric("CAM Std",        f"{float(xai.get('cam_std', 0)):.4f}")

    st.caption("Brighter Grad-CAM regions indicate stronger model-attention for the target class. Not a disease segmentation map.")


# ── Tab 2: Part 4.5 - 3D XAI ────────────────────────────────────────────────

def _tab_part45():
    if not _PART45.exists():
        st.warning("Part 4.5 XAI artifacts not found.")
        return

    st.markdown('<div class="section-title" style="margin-bottom:0.8rem;">Part 4.5 — 3D Gradient Attribution</div>', unsafe_allow_html=True)
    st.caption("3D gradient attribution volumes for each disease class across axial/coronal/sagittal planes.")

    vis_dir = _PART45 / "visualizations"
    if not vis_dir.exists():
        st.warning("Visualization folder not found inside Part 4.5.")
        return

    c_disease, c_orient = st.columns([1.5, 1])
    with c_disease:
        disease = st.selectbox("Select Disease Class", _DISEASE_OPTIONS, key="p45_disease")
    with c_orient:
        orient  = st.selectbox("Select Orientation", ["Axial", "Coronal", "Sagittal"], key="p45_orient")

    file_key = _DISEASE_FILE.get(disease, "")
    orient_key = orient.lower()
    img_path = vis_dir / f"{file_key}_{orient_key}.png"

    if img_path.exists():
        st.markdown(f"**{disease} — {orient}**")
        st.image(str(img_path), use_container_width=True)
        st.caption(f"Part 4.5 — {disease} · {orient} · 3D gradient attribution overlay")
    else:
        st.warning(f"Visualization not found: `{img_path.name}`")
        # Show all available
        avail = list(vis_dir.glob("*.png"))
        if avail:
            st.markdown(f"**{len(avail)} available visualizations:**")
            cols = st.columns(3)
            for i, p in enumerate(sorted(avail)[:9]):
                with cols[i % 3]:
                    st.image(str(p), caption=p.stem, use_container_width=True)

    # Metadata
    meta_path = _PART45 / "part45_3d_xai_metadata.json"
    if meta_path.exists():
        with st.expander("📋 Part 4.5 Metadata"):
            try:
                data = json.loads(meta_path.read_text())
                st.json(data)
            except Exception:
                st.code(meta_path.read_text())


# ── Tab 3: Part 4.6 - Point-Targeted ────────────────────────────────────────

def _tab_part46():
    if not _PART46.exists():
        st.warning("Part 4.6 XAI artifacts not found.")
        return

    st.markdown('<div class="section-title" style="margin-bottom:0.8rem;">Part 4.6 — Point-Targeted 3D XAI</div>', unsafe_allow_html=True)
    st.caption("Targeted attribution around annotated disease points.")

    diseases_avail = [
        "Left Neural Foraminal Narrowing",
        "Right Neural Foraminal Narrowing",
    ]
    c_d, c_o = st.columns([1.5, 1])
    with c_d:
        disease = st.selectbox("Select Disease", diseases_avail, key="p46_disease")
    with c_o:
        orient  = st.selectbox("Select Orientation", ["Axial", "Coronal", "Sagittal"], key="p46_orient")

    file_key = _DISEASE_FILE.get(disease, "")
    orient_key = orient.lower()
    img_path = _PART46 / f"{file_key}_{orient_key}.png"

    if img_path.exists():
        st.image(str(img_path), use_container_width=True)
        st.caption(f"Part 4.6 — {disease} · {orient} plane · point-targeted attribution")
    else:
        # Show all available images
        avail = sorted(_PART46.glob("*.png"))
        if avail:
            st.markdown(f"**{len(avail)} images available in Part 4.6:**")
            cols = st.columns(3)
            for i, p in enumerate(avail[:9]):
                with cols[i % 3]:
                    st.image(str(p), caption=p.stem.replace("_", " ").title(), use_container_width=True)
        else:
            st.info("No visualizations found in Part 4.6 directory.")

    # Summary JSON
    summary_path = _PART46 / "part46_xai_summary.json"
    if summary_path.exists():
        with st.expander("📋 Part 4.6 XAI Summary"):
            try:
                data = json.loads(summary_path.read_text())
                st.json(data)
            except Exception:
                st.code(summary_path.read_text())


# ── Tab 4: Part 4.6B - Multi-Point ──────────────────────────────────────────

def _tab_part46b():
    if not _PART46B.exists():
        st.warning("Part 4.6B XAI artifacts not found.")
        return

    st.markdown('<div class="section-title" style="margin-bottom:0.8rem;">Part 4.6B — Multi-Point / Multi-Level XAI</div>', unsafe_allow_html=True)
    st.caption("Point-targeted XAI across all lumbar levels (L1/L2 – L5/S1).")

    csv_path = _PART46B / "point_results.csv"
    if csv_path.exists():
        try:
            df = pd.read_csv(csv_path)
            # Filters
            fc1, fc2, fc3 = st.columns(3)
            diseases = ["All"] + sorted(df["disease"].unique().tolist()) if "disease" in df.columns else ["All"]
            levels   = ["All"] + sorted(df["level"].unique().tolist())   if "level"   in df.columns else ["All"]

            with fc1:
                f_disease = st.selectbox("Filter: Disease", diseases, key="p46b_fd")
            with fc2:
                f_level   = st.selectbox("Filter: Level",   levels,   key="p46b_fl")
            with fc3:
                f_study   = st.text_input("Filter: Study ID", "", key="p46b_fs")

            filtered = df.copy()
            if f_disease != "All" and "disease" in filtered.columns:
                filtered = filtered[filtered["disease"] == f_disease]
            if f_level != "All" and "level" in filtered.columns:
                filtered = filtered[filtered["level"] == f_level]
            if f_study.strip() and "study_id" in filtered.columns:
                filtered = filtered[filtered["study_id"].astype(str).str.contains(f_study.strip())]

            display_cols = [c for c in [
                "point_index","disease","level","target_probability",
                "centroid_distance","r10_concentration"
            ] if c in filtered.columns]

            st.dataframe(filtered[display_cols].reset_index(drop=True) if display_cols else filtered,
                         use_container_width=True)
            st.caption(f"Showing {len(filtered)} of {len(df)} points")

        except Exception as exc:
            st.error("Failed to load point_results.csv.")
            with st.expander("Technical details"):
                st.exception(exc)
    else:
        st.warning("point_results.csv not found.")

    # Show available visualization images
    for disease_dir in sorted(_PART46B.iterdir()):
        if disease_dir.is_dir():
            pngs = sorted(disease_dir.glob("*.png"))
            if pngs:
                with st.expander(f"🖼️ {disease_dir.name.replace('_',' ')} — {len(pngs)} visualizations"):
                    cols = st.columns(min(3, len(pngs)))
                    for i, p in enumerate(pngs[:6]):
                        with cols[i % min(3, len(pngs))]:
                            st.image(str(p), caption=p.stem, use_container_width=True)


# ── Tab 5: Part 4.6C - Quantitative XAI ─────────────────────────────────────

def _tab_part46c():
    if not _PART46C.exists():
        st.warning("Part 4.6C XAI artifacts not found.")
        return

    st.markdown('<div class="section-title" style="margin-bottom:0.8rem;">Part 4.6C — Quantitative XAI Analysis</div>', unsafe_allow_html=True)
    st.caption("Attribution distance · R10 concentration · Disease comparison · Level-wise analysis")

    # Overall summary metrics
    overall_csv = _PART46C / "part46c_overall_summary.csv"
    if overall_csv.exists():
        try:
            df = pd.read_csv(overall_csv)
            metric_map = {
                "centroid_distance":      ("Centroid Distance",     "voxels"),
                "max_attribution_distance":("Max Attribution Dist.", "voxels"),
                "r10_concentration":      ("R10 Concentration",     "mean"),
            }
            cols = st.columns(len(metric_map))
            for col, (metric, (label, unit)) in zip(cols, metric_map.items()):
                row = df[df["metric"] == metric]
                if not row.empty:
                    mean_val = float(row["mean"].iloc[0])
                    with col:
                        st.metric(label, f"{mean_val:.3f}", help=unit)
        except Exception:
            pass

    # PNG visualizations
    png_map = {
        "part46c_comparison.png":                       "Overall Comparison",
        "part46c_centroid_distance_comparison.png":     "Centroid Distance",
        "part46c_r10_concentration_comparison.png":     "R10 Concentration",
        "part46c_max_attribution_distance_comparison.png": "Max Attribution Distance",
        "part46c_disease_level_heatmap.png":            "Disease-Level Heatmap",
        "part46c_levelwise.png":                        "Level-wise Analysis",
    }

    vis_c1, vis_c2 = st.columns(2)
    cols_cycle = [vis_c1, vis_c2]
    i = 0
    for fname, title in png_map.items():
        p = _PART46C / fname
        if p.exists():
            with cols_cycle[i % 2]:
                st.markdown(f"**{title}**")
                st.image(str(p), use_container_width=True)
            i += 1

    # Disease-wise CSV
    disease_csv = _PART46C / "part46c_disease_summary.csv"
    if disease_csv.exists():
        with st.expander("📊 Disease-wise Quantitative Summary"):
            try:
                st.dataframe(pd.read_csv(disease_csv), use_container_width=True)
            except Exception:
                st.warning("Could not load disease summary CSV.")

    # Level-wise CSV
    level_csv = _PART46C / "part46c_level_summary.csv"
    if level_csv.exists():
        with st.expander("📊 Level-wise Quantitative Summary"):
            try:
                st.dataframe(pd.read_csv(level_csv), use_container_width=True)
            except Exception:
                st.warning("Could not load level summary CSV.")


# ── Tab 6: Part 4.6D - Visual Inspection ─────────────────────────────────────

def _tab_part46d():
    if not _PART46D.exists():
        st.warning("Part 4.6D XAI artifacts not found.")
        return

    st.markdown('<div class="section-title" style="margin-bottom:0.8rem;">Part 4.6D — Visual XAI Inspection</div>', unsafe_allow_html=True)
    st.caption("Disease overview · Point inspection · Level-wise visual comparison")

    # Overview images at top level
    top_pngs = sorted(_PART46D.glob("*.png"))
    if top_pngs:
        st.markdown("**Overview Visualizations**")
        cols = st.columns(min(2, len(top_pngs)))
        for i, p in enumerate(top_pngs[:4]):
            with cols[i % 2]:
                st.image(str(p), caption=p.stem.replace("_", " ").title(), use_container_width=True)

    # Disease overviews sub-directory
    overviews_dir = _PART46D / "disease_overviews"
    if overviews_dir.exists():
        pngs = sorted(overviews_dir.glob("*.png"))
        if pngs:
            with st.expander(f"🦠 Disease Overviews ({len(pngs)} images)"):
                cols = st.columns(3)
                for i, p in enumerate(pngs[:9]):
                    with cols[i % 3]:
                        st.image(str(p), caption=p.stem.replace("_"," ").title(), use_container_width=True)

    # Point inspections sub-directory
    inspections_dir = _PART46D / "point_inspections"
    if inspections_dir.exists():
        pngs = sorted(inspections_dir.glob("*.png"))
        if pngs:
            with st.expander(f"📍 Point Inspections ({len(pngs)} images)"):
                cols = st.columns(3)
                for i, p in enumerate(pngs[:9]):
                    with cols[i % 3]:
                        st.image(str(p), caption=p.stem.replace("_"," ").title(), use_container_width=True)

    # Metrics CSV
    csv_path = _PART46D / "part46d_visual_metrics.csv"
    if csv_path.exists():
        with st.expander("📋 Visual Metrics Table"):
            try:
                st.dataframe(pd.read_csv(csv_path), use_container_width=True)
            except Exception:
                st.warning("Could not load visual metrics CSV.")


# ── Main ─────────────────────────────────────────────────────────────────────

def render_xai():
    _page_header()
    _research_disclaimer()

    tab_labels = [
        "🧠 Classification XAI",
        "Part 4.5 — 3D XAI",
        "Part 4.6 — Point XAI",
        "Part 4.6B — Multi-Point",
        "Part 4.6C — Quantitative",
        "Part 4.6D — Visual Inspection",
    ]

    tabs = st.tabs(tab_labels)

    with tabs[0]:
        _tab_classification_xai()
    with tabs[1]:
        _tab_part45()
    with tabs[2]:
        _tab_part46()
    with tabs[3]:
        _tab_part46b()
    with tabs[4]:
        _tab_part46c()
    with tabs[5]:
        _tab_part46d()

    st.markdown("---")
    c1, c2, c3 = st.columns(3)
    with c1:
        if st.button("🩻 MRI Analysis", key="xai_nav_mri", use_container_width=True):
            navigate("🩻 MRI Analysis")
    with c2:
        if st.button("🧊 3D Localization", key="xai_nav_seg", use_container_width=True, type="primary"):
            navigate("🧠 3D Segmentation")
    with c3:
        if st.button("📄 Generate Report", key="xai_nav_rpt", use_container_width=True):
            navigate("📄 Report")
