"""
PHASE 3 - PART 13
QUANTITATIVE ERROR & FAILURE CASE ANALYSIS

Analyzes the official Part 11 test-set results.

IMPORTANT:
This script does NOT run inference and does NOT retrain the model.
It uses the official test_case_results.csv generated by Part 11.
"""

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

TEST_EVALUATION_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "segmentation"
    / "test_evaluation"
)

CASE_RESULTS_PATH = (
    TEST_EVALUATION_DIR
    / "test_case_results.csv"
)

CLASS_SUMMARY_PATH = (
    TEST_EVALUATION_DIR
    / "test_class_summary.csv"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "segmentation"
    / "error_analysis"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# HEADER
# ============================================================

print("=" * 78)
print("PHASE 3 - PART 13")
print("QUANTITATIVE ERROR & FAILURE CASE ANALYSIS")
print("=" * 78)

print("\nPROJECT ROOT")
print(PROJECT_ROOT)

print("\nPART 11 CASE RESULTS")
print(CASE_RESULTS_PATH)

print("\nOUTPUT DIRECTORY")
print(OUTPUT_DIR)


# ============================================================
# VALIDATION
# ============================================================

if not CASE_RESULTS_PATH.exists():

    raise FileNotFoundError(
        f"\nPart 11 result file was not found:\n"
        f"{CASE_RESULTS_PATH}\n\n"
        f"Run Phase 3 - Part 11 first."
    )


# ============================================================
# LOAD RESULTS
# ============================================================

print("\n" + "=" * 78)
print("LOADING OFFICIAL TEST RESULTS")
print("=" * 78)

df = pd.read_csv(
    CASE_RESULTS_PATH
)

print(
    f"Rows loaded: {len(df)}"
)

print(
    f"Columns detected: {len(df.columns)}"
)


# ============================================================
# DISPLAY COLUMNS
# ============================================================

print("\nDetected columns:")

for column in df.columns:

    print(
        f"  - {column}"
    )


# ============================================================
# FIND IMPORTANT COLUMNS
# ============================================================

def find_column(
    dataframe,
    candidates,
    required=True,
):

    normalized = {
        str(col).lower()
        .replace(" ", "_")
        .replace("-", "_"):
        col
        for col in dataframe.columns
    }

    for candidate in candidates:

        key = (
            candidate.lower()
            .replace(" ", "_")
            .replace("-", "_")
        )

        if key in normalized:

            return normalized[key]

    # Partial matching
    for col in dataframe.columns:

        normalized_col = (
            str(col)
            .lower()
            .replace(" ", "_")
            .replace("-", "_")
        )

        for candidate in candidates:

            candidate_key = (
                candidate.lower()
                .replace(" ", "_")
                .replace("-", "_")
            )

            if candidate_key in normalized_col:

                return col

    if required:

        raise RuntimeError(
            "Required column could not be found.\n"
            f"Candidates: {candidates}\n"
            f"Available columns: "
            f"{list(dataframe.columns)}"
        )

    return None


# ============================================================
# CORE METRIC COLUMNS
# ============================================================

FILE_COL = find_column(
    df,
    [
        "file",
        "filename",
        "case",
        "case_name",
        "study",
    ],
)

MEAN_DICE_COL = find_column(
    df,
    [
        "mean_foreground_dice",
        "mean_dice",
        "foreground_dice",
    ],
)


# ============================================================
# PER-CLASS COLUMNS
# ============================================================

VERTEBRA_DICE_COL = find_column(
    df,
    [
        "vertebrae_dice",
        "vertebra_dice",
    ],
    required=False,
)

CANAL_DICE_COL = find_column(
    df,
    [
        "spinal_canal_dice",
        "canal_dice",
    ],
    required=False,
)

DISC_DICE_COL = find_column(
    df,
    [
        "intervertebral_disc_dice",
        "disc_dice",
    ],
    required=False,
)


# ============================================================
# IOU COLUMNS
# ============================================================

MEAN_IOU_COL = find_column(
    df,
    [
        "mean_foreground_iou",
        "mean_iou",
        "foreground_iou",
    ],
    required=False,
)

VERTEBRA_IOU_COL = find_column(
    df,
    [
        "vertebrae_iou",
        "vertebra_iou",
    ],
    required=False,
)

CANAL_IOU_COL = find_column(
    df,
    [
        "spinal_canal_iou",
        "canal_iou",
    ],
    required=False,
)

DISC_IOU_COL = find_column(
    df,
    [
        "intervertebral_disc_iou",
        "disc_iou",
    ],
    required=False,
)


# ============================================================
# CLEAN DATA
# ============================================================

metric_columns = [
    MEAN_DICE_COL,
    VERTEBRA_DICE_COL,
    CANAL_DICE_COL,
    DISC_DICE_COL,
    MEAN_IOU_COL,
    VERTEBRA_IOU_COL,
    CANAL_IOU_COL,
    DISC_IOU_COL,
]

metric_columns = [
    col
    for col in metric_columns
    if col is not None
]

for column in metric_columns:

    df[column] = pd.to_numeric(
        df[column],
        errors="coerce",
    )


df = df[
    df[MEAN_DICE_COL].notna()
].copy()


# ============================================================
# BASIC DATASET STATISTICS
# ============================================================

print("\n" + "=" * 78)
print("TEST DATASET STATISTICS")
print("=" * 78)

n_cases = len(df)

mean_dice = df[
    MEAN_DICE_COL
].mean()

median_dice = df[
    MEAN_DICE_COL
].median()

std_dice = df[
    MEAN_DICE_COL
].std()

min_dice = df[
    MEAN_DICE_COL
].min()

max_dice = df[
    MEAN_DICE_COL
].max()

q25_dice = df[
    MEAN_DICE_COL
].quantile(0.25)

q75_dice = df[
    MEAN_DICE_COL
].quantile(0.75)


print(
    f"Test cases       : {n_cases}"
)

print(
    f"Mean Dice        : {mean_dice:.6f}"
)

print(
    f"Median Dice      : {median_dice:.6f}"
)

print(
    f"Std Dice         : {std_dice:.6f}"
)

print(
    f"Minimum Dice     : {min_dice:.6f}"
)

print(
    f"Maximum Dice     : {max_dice:.6f}"
)

print(
    f"25th percentile  : {q25_dice:.6f}"
)

print(
    f"75th percentile  : {q75_dice:.6f}"
)


# ============================================================
# PERFORMANCE THRESHOLDS
# ============================================================

print("\n" + "=" * 78)
print("DICE PERFORMANCE DISTRIBUTION")
print("=" * 78)


thresholds = [
    0.50,
    0.60,
    0.70,
    0.80,
    0.90,
]

threshold_rows = []


for threshold in thresholds:

    count = (
        df[MEAN_DICE_COL]
        >= threshold
    ).sum()

    percentage = (
        count
        / n_cases
        * 100
    )

    threshold_rows.append(
        {
            "threshold": threshold,
            "cases_at_or_above": int(count),
            "percentage": percentage,
        }
    )

    print(
        f"Dice >= {threshold:.2f}: "
        f"{count:3d} cases "
        f"({percentage:.2f}%)"
    )


threshold_df = pd.DataFrame(
    threshold_rows
)


# ============================================================
# LOW-PERFORMANCE CASES
# ============================================================

print("\n" + "=" * 78)
print("LOW-PERFORMANCE CASE COUNTS")
print("=" * 78)


failure_thresholds = [
    0.50,
    0.60,
    0.70,
]

failure_rows = []


for threshold in failure_thresholds:

    count = (
        df[MEAN_DICE_COL]
        < threshold
    ).sum()

    percentage = (
        count
        / n_cases
        * 100
    )

    failure_rows.append(
        {
            "dice_below": threshold,
            "cases": int(count),
            "percentage": percentage,
        }
    )

    print(
        f"Dice < {threshold:.2f}: "
        f"{count:3d} cases "
        f"({percentage:.2f}%)"
    )


failure_df = pd.DataFrame(
    failure_rows
)


# ============================================================
# BEST 10 CASES
# ============================================================

print("\n" + "=" * 78)
print("BEST 10 TEST CASES")
print("=" * 78)

best_10 = (
    df.sort_values(
        MEAN_DICE_COL,
        ascending=False,
    )
    .head(10)
)

print(
    best_10[
        [
            FILE_COL,
            MEAN_DICE_COL,
        ]
    ].to_string(
        index=False
    )
)


# ============================================================
# WORST 10 CASES
# ============================================================

print("\n" + "=" * 78)
print("WORST 10 TEST CASES")
print("=" * 78)

worst_10 = (
    df.sort_values(
        MEAN_DICE_COL,
        ascending=True,
    )
    .head(10)
)

print(
    worst_10[
        [
            FILE_COL,
            MEAN_DICE_COL,
        ]
    ].to_string(
        index=False
    )
)


# ============================================================
# PER-CLASS ANALYSIS
# ============================================================

print("\n" + "=" * 78)
print("PER-CLASS ERROR ANALYSIS")
print("=" * 78)


class_columns = {
    "Vertebrae": VERTEBRA_DICE_COL,
    "Spinal Canal": CANAL_DICE_COL,
    "Intervertebral Disc": DISC_DICE_COL,
}


class_rows = []


for class_name, column in class_columns.items():

    if column is None:

        print(
            f"{class_name}: "
            "column not available"
        )

        continue

    values = df[
        column
    ].dropna()

    if len(values) == 0:
        continue

    class_mean = values.mean()
    class_median = values.median()
    class_std = values.std()
    class_min = values.min()
    class_max = values.max()

    below_50 = (
        values < 0.50
    ).sum()

    below_60 = (
        values < 0.60
    ).sum()

    below_70 = (
        values < 0.70
    ).sum()

    above_80 = (
        values >= 0.80
    ).sum()

    above_90 = (
        values >= 0.90
    ).sum()

    print(
        f"\n{class_name}"
    )

    print(
        f"  Mean Dice   : "
        f"{class_mean:.6f}"
    )

    print(
        f"  Median Dice : "
        f"{class_median:.6f}"
    )

    print(
        f"  Std Dice    : "
        f"{class_std:.6f}"
    )

    print(
        f"  Minimum     : "
        f"{class_min:.6f}"
    )

    print(
        f"  Maximum     : "
        f"{class_max:.6f}"
    )

    print(
        f"  Dice < 0.50 : "
        f"{below_50}"
    )

    print(
        f"  Dice < 0.60 : "
        f"{below_60}"
    )

    print(
        f"  Dice < 0.70 : "
        f"{below_70}"
    )

    print(
        f"  Dice >= 0.80: "
        f"{above_80}"
    )

    print(
        f"  Dice >= 0.90: "
        f"{above_90}"
    )

    class_rows.append(
        {
            "class": class_name,
            "mean_dice": class_mean,
            "median_dice": class_median,
            "std_dice": class_std,
            "minimum_dice": class_min,
            "maximum_dice": class_max,
            "below_0.50": below_50,
            "below_0.60": below_60,
            "below_0.70": below_70,
            "at_or_above_0.80": above_80,
            "at_or_above_0.90": above_90,
        }
    )


class_analysis_df = pd.DataFrame(
    class_rows
)


# ============================================================
# IDENTIFY WORST CASE PER CLASS
# ============================================================

print("\n" + "=" * 78)
print("WORST CASE PER ANATOMICAL CLASS")
print("=" * 78)


worst_class_rows = []


for class_name, column in class_columns.items():

    if column is None:
        continue

    valid = df[
        df[column].notna()
    ]

    if len(valid) == 0:
        continue

    worst = valid.loc[
        valid[column].idxmin()
    ]

    print(
        f"{class_name:25s} "
        f"{worst[FILE_COL]} "
        f"Dice = "
        f"{worst[column]:.6f}"
    )

    worst_class_rows.append(
        {
            "class": class_name,
            "case": worst[FILE_COL],
            "dice": worst[column],
        }
    )


worst_class_df = pd.DataFrame(
    worst_class_rows
)


# ============================================================
# CLASS CORRELATION WITH OVERALL DICE
# ============================================================

print("\n" + "=" * 78)
print("CORRELATION WITH OVERALL FOREGROUND DICE")
print("=" * 78)


correlation_rows = []


for class_name, column in class_columns.items():

    if column is None:
        continue

    subset = df[
        [
            MEAN_DICE_COL,
            column,
        ]
    ].dropna()

    if len(subset) < 2:
        continue

    correlation = subset[
        MEAN_DICE_COL
    ].corr(
        subset[column]
    )

    print(
        f"{class_name:25s}: "
        f"{correlation:.6f}"
    )

    correlation_rows.append(
        {
            "class": class_name,
            "correlation_with_overall_dice": correlation,
        }
    )


correlation_df = pd.DataFrame(
    correlation_rows
)


# ============================================================
# IDENTIFY MAIN FAILURE CLASS
# ============================================================

if not class_analysis_df.empty:

    weakest_class_row = (
        class_analysis_df
        .sort_values(
            "mean_dice"
        )
        .iloc[0]
    )

    weakest_class = (
        weakest_class_row["class"]
    )

    weakest_score = (
        weakest_class_row["mean_dice"]
    )

else:

    weakest_class = "Unavailable"
    weakest_score = np.nan


print("\n" + "=" * 78)
print("PRIMARY FAILURE STRUCTURE")
print("=" * 78)

print(
    f"Weakest class: "
    f"{weakest_class}"
)

if not np.isnan(
    weakest_score
):

    print(
        f"Mean Dice: "
        f"{weakest_score:.6f}"
    )


# ============================================================
# PLOT 1
# OVERALL DICE DISTRIBUTION
# ============================================================

print("\n" + "=" * 78)
print("CREATING VISUAL ANALYSIS CHARTS")
print("=" * 78)


plt.figure(
    figsize=(10, 6)
)

plt.hist(
    df[MEAN_DICE_COL],
    bins=10,
)

plt.axvline(
    mean_dice,
    linestyle="--",
    linewidth=2,
    label=f"Mean = {mean_dice:.4f}",
)

plt.axvline(
    median_dice,
    linestyle=":",
    linewidth=2,
    label=f"Median = {median_dice:.4f}",
)

plt.xlabel(
    "Mean Foreground Dice"
)

plt.ylabel(
    "Number of Test Cases"
)

plt.title(
    "Overall Test-Set Dice Distribution"
)

plt.legend()

plt.tight_layout()

overall_distribution_path = (
    OUTPUT_DIR
    / "overall_dice_distribution.png"
)

plt.savefig(
    overall_distribution_path,
    dpi=200,
    bbox_inches="tight",
)

plt.close()

print(
    f"Saved: "
    f"{overall_distribution_path}"
)


# ============================================================
# PLOT 2
# PER-CLASS DICE DISTRIBUTION
# ============================================================

available_class_data = []

available_class_names = []


for class_name, column in class_columns.items():

    if column is not None:

        available_class_data.append(
            df[column].dropna()
        )

        available_class_names.append(
            class_name
        )


if available_class_data:

    plt.figure(
        figsize=(10, 6)
    )

    plt.boxplot(
        available_class_data,
        labels=available_class_names,
    )

    plt.ylabel(
        "Dice Score"
    )

    plt.title(
        "Per-Class Test Dice Distribution"
    )

    plt.ylim(
        0,
        1.05
    )

    plt.tight_layout()

    class_distribution_path = (
        OUTPUT_DIR
        / "per_class_dice_distribution.png"
    )

    plt.savefig(
        class_distribution_path,
        dpi=200,
        bbox_inches="tight",
    )

    plt.close()

    print(
        f"Saved: "
        f"{class_distribution_path}"
    )


# ============================================================
# PLOT 3
# MEAN CLASS DICE
# ============================================================

if not class_analysis_df.empty:

    plt.figure(
        figsize=(10, 6)
    )

    plt.bar(
        class_analysis_df["class"],
        class_analysis_df["mean_dice"],
    )

    plt.ylabel(
        "Mean Dice"
    )

    plt.xlabel(
        "Anatomical Structure"
    )

    plt.title(
        "Mean Dice by Anatomical Structure"
    )

    plt.ylim(
        0,
        1.0
    )

    plt.xticks(
        rotation=15
    )

    plt.tight_layout()

    class_mean_path = (
        OUTPUT_DIR
        / "mean_class_dice.png"
    )

    plt.savefig(
        class_mean_path,
        dpi=200,
        bbox_inches="tight",
    )

    plt.close()

    print(
        f"Saved: "
        f"{class_mean_path}"
    )


# ============================================================
# PLOT 4
# WORST 10 CASES
# ============================================================

worst_plot = (
    df.sort_values(
        MEAN_DICE_COL,
        ascending=True,
    )
    .head(10)
    .copy()
)

plt.figure(
    figsize=(11, 7)
)

plt.barh(
    worst_plot[
        FILE_COL
    ].astype(str),
    worst_plot[
        MEAN_DICE_COL
    ],
)

plt.xlabel(
    "Mean Foreground Dice"
)

plt.ylabel(
    "Test Case"
)

plt.title(
    "10 Worst Test Cases"
)

plt.xlim(
    0,
    1
)

plt.tight_layout()

worst_plot_path = (
    OUTPUT_DIR
    / "worst_10_cases.png"
)

plt.savefig(
    worst_plot_path,
    dpi=200,
    bbox_inches="tight",
)

plt.close()

print(
    f"Saved: "
    f"{worst_plot_path}"
)


# ============================================================
# PLOT 5
# BEST 10 CASES
# ============================================================

best_plot = (
    df.sort_values(
        MEAN_DICE_COL,
        ascending=False,
    )
    .head(10)
    .sort_values(
        MEAN_DICE_COL
    )
    .copy()
)

plt.figure(
    figsize=(11, 7)
)

plt.barh(
    best_plot[
        FILE_COL
    ].astype(str),
    best_plot[
        MEAN_DICE_COL
    ],
)

plt.xlabel(
    "Mean Foreground Dice"
)

plt.ylabel(
    "Test Case"
)

plt.title(
    "10 Best Test Cases"
)

plt.xlim(
    0,
    1
)

plt.tight_layout()

best_plot_path = (
    OUTPUT_DIR
    / "best_10_cases.png"
)

plt.savefig(
    best_plot_path,
    dpi=200,
    bbox_inches="tight",
)

plt.close()

print(
    f"Saved: "
    f"{best_plot_path}"
)


# ============================================================
# PLOT 6
# CLASS VS OVERALL DICE
# ============================================================

for class_name, column in class_columns.items():

    if column is None:
        continue

    subset = df[
        [
            MEAN_DICE_COL,
            column,
        ]
    ].dropna()

    if len(subset) < 2:
        continue

    plt.figure(
        figsize=(8, 6)
    )

    plt.scatter(
        subset[MEAN_DICE_COL],
        subset[column],
    )

    plt.xlabel(
        "Overall Foreground Dice"
    )

    plt.ylabel(
        f"{class_name} Dice"
    )

    plt.title(
        f"Overall Dice vs {class_name} Dice"
    )

    plt.xlim(
        0,
        1
    )

    plt.ylim(
        0,
        1
    )

    plt.grid(
        alpha=0.25
    )

    plt.tight_layout()

    safe_name = (
        class_name
        .lower()
        .replace(" ", "_")
    )

    correlation_path = (
        OUTPUT_DIR
        / f"overall_vs_{safe_name}_dice.png"
    )

    plt.savefig(
        correlation_path,
        dpi=200,
        bbox_inches="tight",
    )

    plt.close()

    print(
        f"Saved: "
        f"{correlation_path}"
    )


# ============================================================
# SAVE CSV RESULTS
# ============================================================

print("\n" + "=" * 78)
print("SAVING ANALYSIS TABLES")
print("=" * 78)


threshold_df.to_csv(
    OUTPUT_DIR
    / "dice_threshold_distribution.csv",
    index=False,
)

failure_df.to_csv(
    OUTPUT_DIR
    / "dice_failure_counts.csv",
    index=False,
)

class_analysis_df.to_csv(
    OUTPUT_DIR
    / "per_class_error_analysis.csv",
    index=False,
)

worst_class_df.to_csv(
    OUTPUT_DIR
    / "worst_case_per_class.csv",
    index=False,
)

correlation_df.to_csv(
    OUTPUT_DIR
    / "class_overall_correlation.csv",
    index=False,
)

best_10.to_csv(
    OUTPUT_DIR
    / "best_10_test_cases.csv",
    index=False,
)

worst_10.to_csv(
    OUTPUT_DIR
    / "worst_10_test_cases.csv",
    index=False,
)


# ============================================================
# REPORT
# ============================================================

report_path = (
    OUTPUT_DIR
    / "phase3_part13_error_analysis_report.txt"
)


with open(
    report_path,
    "w",
    encoding="utf-8",
) as report:

    report.write(
        "PHASE 3 - PART 13\n"
    )

    report.write(
        "QUANTITATIVE ERROR & FAILURE "
        "CASE ANALYSIS\n"
    )

    report.write(
        "=" * 70 + "\n\n"
    )

    report.write(
        "DATA SOURCE\n"
    )

    report.write(
        f"{CASE_RESULTS_PATH}\n\n"
    )

    report.write(
        "TEST DATASET\n"
    )

    report.write(
        f"Test cases: {n_cases}\n"
    )

    report.write(
        f"Mean Foreground Dice: "
        f"{mean_dice:.6f}\n"
    )

    report.write(
        f"Median Foreground Dice: "
        f"{median_dice:.6f}\n"
    )

    report.write(
        f"Standard Deviation: "
        f"{std_dice:.6f}\n"
    )

    report.write(
        f"Minimum Dice: "
        f"{min_dice:.6f}\n"
    )

    report.write(
        f"Maximum Dice: "
        f"{max_dice:.6f}\n"
    )

    report.write(
        f"25th Percentile: "
        f"{q25_dice:.6f}\n"
    )

    report.write(
        f"75th Percentile: "
        f"{q75_dice:.6f}\n\n"
    )

    report.write(
        "PERFORMANCE THRESHOLDS\n"
    )

    report.write(
        "-" * 70 + "\n"
    )

    for _, row in threshold_df.iterrows():

        report.write(
            f"Dice >= "
            f"{row['threshold']:.2f}: "
            f"{int(row['cases_at_or_above'])} "
            f"cases "
            f"({row['percentage']:.2f}%)\n"
        )

    report.write(
        "\nFAILURE COUNTS\n"
    )

    report.write(
        "-" * 70 + "\n"
    )

    for _, row in failure_df.iterrows():

        report.write(
            f"Dice < "
            f"{row['dice_below']:.2f}: "
            f"{int(row['cases'])} "
            f"cases "
            f"({row['percentage']:.2f}%)\n"
        )

    report.write(
        "\nPER-CLASS ANALYSIS\n"
    )

    report.write(
        "-" * 70 + "\n"
    )

    for _, row in class_analysis_df.iterrows():

        report.write(
            f"\n{row['class']}\n"
        )

        report.write(
            f"Mean Dice: "
            f"{row['mean_dice']:.6f}\n"
        )

        report.write(
            f"Median Dice: "
            f"{row['median_dice']:.6f}\n"
        )

        report.write(
            f"Std Dice: "
            f"{row['std_dice']:.6f}\n"
        )

        report.write(
            f"Minimum Dice: "
            f"{row['minimum_dice']:.6f}\n"
        )

        report.write(
            f"Maximum Dice: "
            f"{row['maximum_dice']:.6f}\n"
        )

        report.write(
            f"Dice < 0.50: "
            f"{int(row['below_0.50'])}\n"
        )

        report.write(
            f"Dice < 0.60: "
            f"{int(row['below_0.60'])}\n"
        )

        report.write(
            f"Dice < 0.70: "
            f"{int(row['below_0.70'])}\n"
        )

        report.write(
            f"Dice >= 0.80: "
            f"{int(row['at_or_above_0.80'])}\n"
        )

        report.write(
            f"Dice >= 0.90: "
            f"{int(row['at_or_above_0.90'])}\n"
        )

    report.write(
        "\nWORST CASE PER CLASS\n"
    )

    report.write(
        "-" * 70 + "\n"
    )

    for _, row in worst_class_df.iterrows():

        report.write(
            f"{row['class']}: "
            f"{row['case']} | "
            f"Dice = "
            f"{row['dice']:.6f}\n"
        )

    report.write(
        "\nCLASS / OVERALL DICE CORRELATION\n"
    )

    report.write(
        "-" * 70 + "\n"
    )

    for _, row in correlation_df.iterrows():

        report.write(
            f"{row['class']}: "
            f"{row['correlation_with_overall_dice']:.6f}\n"
        )

    report.write(
        "\nPRIMARY FAILURE STRUCTURE\n"
    )

    report.write(
        "-" * 70 + "\n"
    )

    report.write(
        f"{weakest_class}\n"
    )

    report.write(
        f"Mean Dice: "
        f"{weakest_score:.6f}\n"
    )

    report.write(
        "\nBEST 10 CASES\n"
    )

    report.write(
        "-" * 70 + "\n"
    )

    for _, row in best_10.iterrows():

        report.write(
            f"{row[FILE_COL]}: "
            f"{row[MEAN_DICE_COL]:.6f}\n"
        )

    report.write(
        "\nWORST 10 CASES\n"
    )

    report.write(
        "-" * 70 + "\n"
    )

    for _, row in worst_10.iterrows():

        report.write(
            f"{row[FILE_COL]}: "
            f"{row[MEAN_DICE_COL]:.6f}\n"
        )


# ============================================================
# FINAL OUTPUT
# ============================================================

print("\n" + "=" * 78)
print("PART 13 OUTPUT")
print("=" * 78)

print(
    f"Output directory:\n"
    f"{OUTPUT_DIR}"
)

print(
    f"\nReport:\n"
    f"{report_path}"
)

print(
    "\n✓ Quantitative error analysis complete."
)

print("\n" + "=" * 78)
print("PHASE 3 - PART 13 COMPLETE")
print("=" * 78)