from pathlib import Path
import json
import numpy as np
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[1]

XAI_DIR = ROOT / "outputs" / "segmentation" / "rsna_part45_3d_xai"

NPZ = XAI_DIR / "part45_3d_xai_volumes.npz"
META = XAI_DIR / "part45_3d_xai_metadata.json"

IMAGE_NPY = XAI_DIR / "input_image.npy"

STUDY_ID = "7143189"
SERIES_ID = "3219733239"

CLASS_NAMES = {
    1: "Spinal Canal Stenosis",
    2: "Left Neural Foraminal Narrowing",
    3: "Right Neural Foraminal Narrowing",
    4: "Left Subarticular Stenosis",
    5: "Right Subarticular Stenosis",
}


def slice_volume(volume, orientation, index):
    if orientation == "Axial":
        return volume[index, :, :]
    if orientation == "Coronal":
        return volume[:, index, :]
    return volume[:, :, index]


def main():

    print("=" * 80)
    print("PART 4.5B")
    print("3D XAI VISUALIZATION")
    print("=" * 80)

    if not NPZ.exists():
        raise FileNotFoundError(NPZ)

    data = np.load(NPZ)

    print(f"Study ID : {STUDY_ID}")
    print(f"Series ID: {SERIES_ID}")

    print()
    print("Available XAI volumes:")

    for key in data.files:
        print(
            f"  {key}: {data[key].shape}"
        )

    print()
    print("NOTE:")
    print(
        "This visualization uses the model-derived "
        "3D attribution volumes generated by Part 4.5."
    )

    # --------------------------------------------------------------
    # Because Part 4.5 did not save the MRI itself, load it through
    # the exact physical-space pipeline again.
    # --------------------------------------------------------------

    import sys

    SRC = ROOT / "src"

    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))

    if str(SRC) not in sys.path:
        sys.path.insert(0, str(SRC))

    import segmentation_rsna_part220b_geometry_corrected_training as part220b

    manifest = part220b.load_manifest()

    point_df = manifest[
        (manifest["study_id"].astype(str) == STUDY_ID)
        &
        (manifest["series_id"].astype(str) == SERIES_ID)
    ].copy()

    loaded = part220b.load_case(
        STUDY_ID,
        SERIES_ID,
        point_df,
    )

    if len(loaded) == 3:
        image, points, geometry = loaded
    else:
        image, points, geometry, _ = loaded

    image = np.asarray(
        image,
        dtype=np.float32,
    )

    print(
        f"MRI shape: {image.shape}"
    )

    OUTPUT = (
        XAI_DIR
        / "visualizations"
    )

    OUTPUT.mkdir(
        parents=True,
        exist_ok=True,
    )

    # --------------------------------------------------------------
    # Visualize central slice of each orientation
    # --------------------------------------------------------------

    orientations = [
        "Axial",
        "Coronal",
        "Sagittal",
    ]

    for class_id, class_name in CLASS_NAMES.items():

        safe_name = (
            class_name
            .lower()
            .replace(" ", "_")
            .replace("/", "_")
        )

        xai_key = (
            f"{safe_name}_xai"
        )

        prob_key = (
            f"{safe_name}_probability"
        )

        if xai_key not in data.files:
            print(
                f"Skipping {class_name}: "
                f"XAI volume missing."
            )
            continue

        xai = data[xai_key]
        probability = data[prob_key]

        for orientation in orientations:

            if orientation == "Axial":
                index = image.shape[0] // 2

            elif orientation == "Coronal":
                index = image.shape[1] // 2

            else:
                index = image.shape[2] // 2

            img2d = slice_volume(
                image,
                orientation,
                index,
            )

            xai2d = slice_volume(
                xai,
                orientation,
                index,
            )

            prob2d = slice_volume(
                probability,
                orientation,
                index,
            )

            fig, ax = plt.subplots(
                1,
                4,
                figsize=(20, 5),
            )

            # MRI
            finite = img2d[
                np.isfinite(img2d)
            ]

            lo, hi = np.percentile(
                finite,
                [1, 99],
            )

            ax[0].imshow(
                img2d,
                cmap="gray",
                origin="lower",
                vmin=lo,
                vmax=hi,
            )

            ax[0].set_title(
                f"MRI\n{orientation}"
            )

            # Probability
            im1 = ax[1].imshow(
                prob2d,
                cmap="magma",
                origin="lower",
                vmin=0,
                vmax=1,
            )

            ax[1].set_title(
                "Disease Probability"
            )

            fig.colorbar(
                im1,
                ax=ax[1],
                fraction=.046,
                pad=.04,
            )

            # XAI
            im2 = ax[2].imshow(
                xai2d,
                cmap="viridis",
                origin="lower",
                vmin=0,
                vmax=1,
            )

            ax[2].set_title(
                "3D Gradient Attribution"
            )

            fig.colorbar(
                im2,
                ax=ax[2],
                fraction=.046,
                pad=.04,
            )

            # Overlay
            ax[3].imshow(
                img2d,
                cmap="gray",
                origin="lower",
                vmin=lo,
                vmax=hi,
            )

            ax[3].imshow(
                xai2d,
                cmap="jet",
                origin="lower",
                vmin=0,
                vmax=1,
                alpha=0.45,
            )

            ax[3].set_title(
                "MRI + XAI"
            )

            fig.suptitle(
                f"Part 4.5B — {class_name}\n"
                f"{orientation} slice {index}",
                fontsize=14,
            )

            fig.tight_layout()

            output_file = (
                OUTPUT
                /
                f"{safe_name}_{orientation.lower()}.png"
            )

            fig.savefig(
                output_file,
                dpi=150,
                bbox_inches="tight",
            )

            plt.close(fig)

            print(
                f"Saved: {output_file.name}"
            )

    print()
    print("=" * 80)
    print("PART 4.5B COMPLETE")
    print("=" * 80)

    print(
        f"Visualization directory:\n{OUTPUT}"
    )


if __name__ == "__main__":
    main()
